### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by PLUCS2** [fdiengott/Pebbble#2]
- [x] The Users table should have a firstname and a lastname column (they are required for signup on dribbble) - I believe the username just ends up being the first name 
- [x] There is also a location option for Users 
- [x] Do all cards have to belong to a collection? 
- [x] It appears that there are also companies on Dribbble - do you plan on implementing these? If yes, how? 

Nice work! Let me know if you have any questions

**Comment by fdiengott** [comment]
On the signup page, there are two name fields but one is for general name and the other for username. Because there must be a uniqueness constraint I've decided to keep the username field, but am adding the name field. 
All cards do not need to belong to a collection. Collections are a group of saved cards. How would I denote them as optional within the table? I put it in a comment below. 
I do not plan on implementing company profiles.

**Comment by PLUCS2** [comment]
That is perfect - nice work!
